import { Lead } from "@/types/crm";

export const mockAvailableLeads: Lead[] = [
  {
    id: "1",
    firstName: "Pierre",
    lastName: "Martin",
    email: "pierre.martin@email.com",
    phone: "06 12 34 56 78",
    address: "15 rue des Lilas",
    postalCode: "75001",
    city: "Paris",
    projectType: "professional",
    budget: 45000,
    status: "qualified",
    notes: "Installation photovoltaïque pour restaurant 250m²",
    createdAt: "2024-03-20",
    price: 59
  },
  {
    id: "2",
    firstName: "Marie",
    lastName: "Dubois",
    email: "marie.dubois@email.com",
    phone: "06 23 45 67 89",
    address: "8 avenue du Soleil",
    postalCode: "69001",
    city: "Lyon",
    projectType: "residential",
    budget: 15000,
    status: "qualified",
    notes: "Maison individuelle 120m², orientation sud",
    createdAt: "2024-03-19",
    price: 35
  },
  {
    id: "3",
    firstName: "Thomas",
    lastName: "Bernard",
    email: "thomas.bernard@email.com",
    phone: "06 34 56 78 90",
    address: "25 rue de la Paix",
    postalCode: "33000",
    city: "Bordeaux",
    projectType: "professional",
    budget: 65000,
    status: "qualified",
    notes: "Entrepôt logistique 500m², forte consommation",
    createdAt: "2024-03-18",
    price: 59
  },
  {
    id: "4",
    firstName: "Sophie",
    lastName: "Petit",
    email: "sophie.petit@email.com",
    phone: "06 45 67 89 01",
    address: "12 boulevard des Fleurs",
    postalCode: "13001",
    city: "Marseille",
    projectType: "residential",
    budget: 18000,
    status: "qualified",
    notes: "Villa avec piscine, projet d'autoconsommation",
    createdAt: "2024-03-17",
    price: 35
  },
  {
    id: "5",
    firstName: "Lucas",
    lastName: "Roux",
    email: "lucas.roux@email.com",
    phone: "06 56 78 90 12",
    address: "5 rue du Commerce",
    postalCode: "31000",
    city: "Toulouse",
    projectType: "professional",
    budget: 55000,
    status: "qualified",
    notes: "Supermarché, projet d'optimisation énergétique",
    createdAt: "2024-03-16",
    price: 59
  }
];